tgbot:
  labels:
    io.rancher.scheduler.affinity:host_label: owner=fred
    io.rancher.container.pull_image: always
  image: webofmars/incodwetrustbot:develop
  volumes:
    - /var/apps/incodwetrustbot/photos:/usr/src/app/photos
    - /var/apps/incodwetrustbot/games:/usr/src/app/games
  stdin_open: true
  tty: false
  environment:
    GALLERY_URL: "https://icwt.services.webofmars.com/gallery"
    PHOTOS_DIRECTORY: "photos"
    TELEGRAM_BOT_TOKEN: "193218920:AAG9G1zm9K1EFaIHt4HgCwv3AkM0JJozlYA"
    REDIS_HOST: "redis"
    REDIS_PORT: "6379"
    EVENT_DOC_URL: "https://s3.eu-central-1.amazonaws.com/incodwetrust-statics/Prog-InCodWeTrust-EN-2016-v1.pdf"
    EVENT_GAMES_PREFIX: "https://icwt.services.webofmars.com/games/"
  links:
    - redis

redis:
  labels:
    io.rancher.scheduler.affinity:host_label: owner=fred
    io.rancher.container.pull_image: always
  image: redis
  entrypoint:
    - 'redis-server'
    - '--appendonly'
    - 'yes'
  volumes:
  - /var/apps/incodwetrustbot/redis:/data
  stdin_open: true
  tty: false

admin:
  labels:
    io.rancher.scheduler.affinity:host_label: owner=fred
    io.rancher.container.pull_image: always
  image: tenstartups/redis-commander
  links:
    - redis
  stdin_open: true
  tty: false
  entrypoint:
    - 'redis-commander'
    - '--redis-host'
    - 'redis'
