tgbot:
  labels:
    io.rancher.scheduler.affinity:host_label: owner=fred
    io.rancher.container.pull_image: always
  image: webofmars/incodwetrustbot:develop
  volumes:
  - /var/apps/incodwetrustbot/photos:/usr/src/app/photos
  stdin_open: true
  tty: true
