tgbot:
  build: ../
  volumes:
    - ../lib:/usr/src/app/lib
    - ../public:/usr/src/app/public
    - ../games:/usr/src/app/games
    - ../bot.js:/usr/src/app/bot.js
    - ../node-gallery:/usr/src/app/node-gallery
    - ../package.json:/usr/src/app/package.json
  stdin_open: true
  tty: false
  environment:
    GALLERY_URL: "http://localhost:3000/gallery"
    PHOTOS_DIRECTORY: "photos"
    TELEGRAM_BOT_TOKEN: "253051372:AAFSbfRIxPNGeeBStSxAOJMY-Y5rEDoXtCk"
    REDIS_HOST: "redis"
    REDIS_PORT: "6379"
    EVENT_DOC_URL: "https://s3.eu-central-1.amazonaws.com/incodwetrust-statics/Prog-InCodWeTrust-EN-2016-v6.pdf"
    EVENT_GAMES_PREFIX: "http://localhost:3000/gallery/games/"
  ports:
    - 3000:3000
    - 5858:5858
    - 8080:8080
  links:
    - redis

redis:
  image: redis
  entrypoint:
     - 'redis-server'
     - '--appendonly'
     - 'yes'
  volumes:
  - ../redis:/data
  stdin_open: true
  tty: false

admin:
  image: tenstartups/redis-commander
  links:
    - redis
  stdin_open: true
  tty: false
  ports:
    - 8081:8081
  entrypoint:
    - 'redis-commander'
    - '--redis-host'
    - 'redis'
