tgbot:
  ports:
  - 3000/tcp
  log_driver: ''
  labels:
    io.rancher.scheduler.affinity:host_label: owner=fred
  tty: true
  log_opt: {}
  image: webofmars/incodwetrustbot:latest
  volumes:
  - /var/apps/incodwetrustbot/photos:/usr/src/app/photos
  stdin_open: true