version: '2.1'
services:

telegram_bot:
  scale: 1
  health_check:
    port: 3000
    interval: 2000
    initializing_timeout: 60000
    unhealthy_threshold: 3
    strategy: recreate
    healthy_threshold: 2
    response_timeout: 2000

database:
  scale: 1
  health_check:
    port: 6379
    interval: 2000
    initializing_timeout: 60000
    unhealthy_threshold: 3
    strategy: recreate
    healthy_threshold: 2
    response_timeout: 2000

db_admin:
  scale: 1
  health_check:
    port: 8081
    interval: 2000
    initializing_timeout: 60000
    unhealthy_threshold: 3
    strategy: recreate
    healthy_threshold: 2
    response_timeout: 2000
